mongodb:
  db:
    conn: ""
    db: ""
    ca_file: 

hot_topic_management:
  app:
    filt_path:
  repo:
    Community_collections:
    - community: openubmc
      hot_topic: openubmc_hot_topic
      not_hot_topic: openubmc_not_hot_topic

    - community: cann
      hot_topic: cann_hot_topic
      not_hot_topic: cann_not_hot_topic
